"""Build Manager.

빌드 옵션은 development / release 두 프로필로 구분한다 (BuildProfile).

  development: 디버깅 우선 — dev 서버(HMR/--reload), 소스맵, 리소스 절반, 단일 replica,
               이미지 태그에 "-dev" 접미사, {name}-dev.{base_domain} 도메인.
  release:     운영 최적화 — 프로덕션 빌드(minify), 멀티스테이지 이미지, 리소스 전량,
               2차(k8s)에서는 replicas 2 + 롤링 업데이트.

프로젝트 리포에 Dockerfile이 있으면 그것을 우선하고(--build-arg APP_PROFILE 전달),
없으면 templates/dockerfiles/{type}.{profile}.Dockerfile 템플릿을 사용한다.
"""
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from ..config import get_settings
from ..models import BuildProfile, Project, ProjectType
from .git_auth import auth_args

# git 출력은 로케일이 아니라 UTF-8로 읽는다 — 한글 경로·문서가 섞이면
# 로케일 인코딩(POSIX/cp949)에서 디코딩이 깨져 요청 전체가 실패한다.
_TEXT = {"text": True, "encoding": "utf-8", "errors": "replace"}

TEMPLATE_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "dockerfiles"
START_SCRIPT_NAME = "start.cmd"

# windows_service 런타임용 제네릭 시작 스크립트. 타입별 규칙 없이 리포 시그니처
# (package.json / requirements.txt / app.py)로 실행 방법을 런타임에 추정한다.
# PORT/HOST는 windows_service 런타임이 주입한다(HOST=127.0.0.1로 로컬 바인드).
PREVIEW_CONFIG_NAME = "paas-preview.config.mjs"

# vite preview는 Host 헤더를 검사해서, 리버스 프록시가 넘겨준 공개 도메인 이름을
# "Blocked request. This host is not allowed."로 거절한다. 그 검사는 개발용 서버가
# 사설망 밖에서 접근되는 것(DNS rebinding)을 막기 위한 것인데, 이 배포는 프록시만
# 닿는 127.0.0.1 뒤라 해당하지 않는다.
#
# allowedHosts는 CLI 옵션이 없어 설정 파일로만 줄 수 있다(vite의 preview 명령은
# host/port/strictPort/open/outDir만 받는다). 그렇다고 이 파일로 프로젝트 설정을
# 대체하면 base·outDir 같은 값이 사라지므로, 프로젝트 자신의 vite.config를 읽어
# 그 위에 얹는다. 이 파일 이름은 vite가 기본으로 찾는 이름이 아니라서
# loadConfigFromFile이 자기 자신을 다시 읽는 일은 없다.
_PREVIEW_CONFIG = """// 플랫폼 자동 생성 — 배포마다 덮어쓴다. 직접 고치지 말 것.
import { defineConfig, loadConfigFromFile, mergeConfig } from 'vite'

export default defineConfig(async (env) => {
  const loaded = await loadConfigFromFile(env)
  return mergeConfig(loaded?.config ?? {}, {
    preview: { allowedHosts: true },
    // dev 서버도 같은 Host 검사를 한다 — dev 프로필은 이 설정으로 띄운다.
    server: { allowedHosts: true },
  })
})
"""

# **생성되는 배치는 ASCII만 쓴다.** cmd.exe는 이 파일을 콘솔 코드페이지로 읽는다(한국어
# 윈도우는 949). UTF-8 한글이 섞이면 2바이트 판독이 어긋나 줄 경계가 밀리고, 다음 줄의
# `REM`이 먹히면서 주석이 **명령으로 실행**된다 — 실측(codepage 949)에서 이 템플릿은
# 기동 전에 rc=255로 죽었고, 화면에는 nssm의 "SERVICE_PAUSED"만 남았다(negowith).
#
# cp949로 저장하면 동작하지만, 그건 그 코드페이지 서버에서만 맞다 — 파일을 로케일에 묶지
# 않고 ASCII로 쓰는 쪽이 어느 코드페이지에서도 옳다. 그래서 "왜 이렇게 했는가"는 여기
# 파이썬 주석에 남기고, 배치에는 짧은 영어 주석만 둔다. 아래 세 가지가 특히 그렇다.
#
# 1. STREAMLIT_FLAGS를 if 체인 **밖에서** 정한다. 괄호 블록은 통째로 한 번 파싱되므로,
#    블록 안에서 set한 변수는 같은 블록에서 %VAR%로 읽히지 않는다.
# 2. 같은 이유로 판정에는 %errorlevel%이 아니라 실행 시점에 평가되는 `if errorlevel`을
#    쓴다(예전에 이 함정으로 vite 분기가 한 번도 실행되지 않았다).
# 3. package.json의 스크립트 존재 여부는 node로 직접 읽는다 — 텍스트 검색은 "start:dev"나
#    "pre-start" 같은 다른 이름에도 걸린다.
_START_SCRIPT = """@echo off
REM Generated by the platform (windows_service runtime). PORT/HOST are injected.
REM ASCII ONLY - see build.py for why (cmd.exe misparses non-ASCII under DBCS codepages).
REM UTF-8 mode: pip decodes requirements.txt with the locale codepage unless this is set,
REM and one non-ASCII comment line then fails the whole install (build.py explains).
set PYTHONUTF8=1
if not defined PORT set PORT=8000
if not defined HOST set HOST=127.0.0.1
set PORT=%PORT%
set HOST=%HOST%
REM Streamlit flags are set OUTSIDE the if-chain below on purpose (build.py explains).
set STREAMLIT_FLAGS=--server.headless true --server.enableCORS false --server.enableXsrfProtection false

if exist package.json (
  REM The deploy step already installed dependencies (build.install_dependencies).
  REM Installing again here would repeat on every service start. Last-resort only.
  if not exist node_modules (
    echo [PaaS Auto-Provisioning] node_modules missing - installing as a fallback.
    call npm install
  )
  REM development profile: run the project's own dev script. The platform passes the
  REM port/host it assigned, the public base path, and the Host-check config.
  if /I "%PAAS_PROFILE%"=="development" (
    node -e "var p=require('./package.json');var s=p.scripts?p.scripts.dev:0;process.exit(s?0:1)" >nul 2>&1
    if errorlevel 1 (
      if exist node_modules\\.bin\\vite.cmd (
        echo [PaaS Auto-Provisioning] No "dev" script - starting Vite directly.
        node_modules\\.bin\\vite.cmd --config paas-preview.config.mjs --host %HOST% --port %PORT% --base %PAAS_BASE_PATH%
      ) else (
        echo [PaaS] development profile needs a "dev" script in package.json, or vite installed.
        exit /b 1
      )
    ) else (
      echo [PaaS Auto-Provisioning] development profile - running "npm run dev".
      call npm run dev -- --config paas-preview.config.mjs --host %HOST% --port %PORT% --base %PAAS_BASE_PATH%
    )
    goto :eof
  )
  REM Vite scaffolding has no "start" script - serve the build via "vite preview".
  REM Read package.json with node instead of a text search, and branch on
  REM "if errorlevel" (not %errorlevel%) - build.py explains both.
  node -e "var p=require('./package.json');var s=p.scripts?p.scripts.start:0;process.exit(s?0:1)" >nul 2>&1
  if errorlevel 1 (
    if exist node_modules\\.bin\\vite.cmd (
      echo [PaaS Auto-Provisioning] No "start" script in package.json - serving the Vite build via "vite preview".
      node_modules\\.bin\\vite.cmd preview --config paas-preview.config.mjs --host %HOST% --port %PORT%
    ) else (
      echo [PaaS] No "start" script and node_modules\\.bin\\vite.cmd is missing.
      echo [PaaS] Dependencies may have been installed without devDependencies -
      echo [PaaS] check NODE_ENV=production or omit=dev/production in .npmrc.
      npm start
    )
  ) else (
    npm start
  )
) else if exist requirements.txt (
  if not exist .venv (
    echo [PaaS Auto-Provisioning] Python venv missing. Creating .venv...
    py -m venv .venv || python -m venv .venv || python3 -m venv .venv
  )
  if exist .venv\\Scripts\\activate.bat (
    call .venv\\Scripts\\activate.bat
  ) else if exist .venv/bin/activate (
    call .venv/bin/activate
  )
  echo [PaaS Auto-Provisioning] Installing Python dependencies from requirements.txt...
  python -m pip install --upgrade pip --disable-pip-version-check
  python -m pip install --disable-pip-version-check -r requirements.txt
  REM A streamlit app does not start under uvicorn. Same test as structure._is_streamlit;
  REM CORS/XSRF are disabled because this runs behind the platform proxy (as in the Dockerfile).
  findstr /I /R "^streamlit" requirements.txt >nul 2>&1
  if errorlevel 1 (
    echo [PaaS Auto-Provisioning] starting with uvicorn.
  ) else if exist app\\streamlit_app.py (
    python -m streamlit run app\\streamlit_app.py --server.port %PORT% --server.address %HOST% %STREAMLIT_FLAGS%
    exit /b
  ) else if exist streamlit_app.py (
    python -m streamlit run streamlit_app.py --server.port %PORT% --server.address %HOST% %STREAMLIT_FLAGS%
    exit /b
  ) else if exist app.py (
    python -m streamlit run app.py --server.port %PORT% --server.address %HOST% %STREAMLIT_FLAGS%
    exit /b
  ) else if exist main.py (
    python -m streamlit run main.py --server.port %PORT% --server.address %HOST% %STREAMLIT_FLAGS%
    exit /b
  ) else (
    echo [PaaS] streamlit app but no entry file found -
    echo [PaaS] one of app/streamlit_app.py, streamlit_app.py, app.py, main.py is required.
    exit /b 1
  )
  if exist app\\main.py (
    python -m uvicorn app.main:app --host %HOST% --port %PORT%
  ) else if exist main.py (
    python -m uvicorn main:app --host %HOST% --port %PORT%
  ) else if exist app.py (
    python -m uvicorn app:app --host %HOST% --port %PORT%
  ) else (
    python -m uvicorn app.main:app --host %HOST% --port %PORT%
  )
) else if exist main.py (
  if not exist .venv (
    echo [PaaS Auto-Provisioning] Creating .venv for main.py...
    py -m venv .venv || python -m venv .venv
  )
  if exist .venv\\Scripts\\activate.bat call .venv\\Scripts\\activate.bat
  python -m uvicorn main:app --host %HOST% --port %PORT%
) else if exist app.py (
  if not exist .venv (
    echo [PaaS Auto-Provisioning] Creating .venv for app.py...
    py -m venv .venv || python -m venv .venv
  )
  if exist .venv\\Scripts\\activate.bat call .venv\\Scripts\\activate.bat
  python -m uvicorn app:app --host %HOST% --port %PORT%
) else if exist index.html (
  py -m http.server %PORT% --bind %HOST%
) else (
  REM Fail here on purpose. Serving a repo we cannot start would publish its sources
  REM (and any committed .env) as a static file listing - build.py explains.
  echo [PaaS] Cannot tell how to start this repo. One of these is required:
  echo [PaaS]   package.json ^(node/react^), requirements.txt ^(python/streamlit^)
  echo [PaaS]   main.py, app.py ^(python^), index.html ^(static^)
  echo [PaaS] If the sources live in a subfolder, set the project's source_subdir.
  exit /b 1
)
"""

# 프로젝트 타입별 컨테이너 내부 포트. (react release는 정적 파일을 caddy로 서빙)
INTERNAL_PORTS: dict[tuple[ProjectType, BuildProfile], int] = {
    (ProjectType.react, BuildProfile.development): 3000,
    (ProjectType.react, BuildProfile.release): 80,
    (ProjectType.node, BuildProfile.development): 3000,
    (ProjectType.node, BuildProfile.release): 3000,
    (ProjectType.python, BuildProfile.development): 8000,
    (ProjectType.python, BuildProfile.release): 8000,
    (ProjectType.llm, BuildProfile.development): 8000,
    (ProjectType.llm, BuildProfile.release): 8000,
    (ProjectType.html, BuildProfile.development): 80,
    (ProjectType.html, BuildProfile.release): 80,
    (ProjectType.streamlit, BuildProfile.development): 8501,
    (ProjectType.streamlit, BuildProfile.release): 8501,
}


@dataclass
class ProfileSpec:
    """프로필이 빌드·배포 전반에 미치는 효과를 한 곳에 모은 정의."""

    profile: BuildProfile
    tag_suffix: str
    env: dict[str, str]
    resource_factor: float  # release 대비 리소스 배율
    replicas: int  # 2차(k8s)에서 사용. 1차는 항상 1.

    def image_tag(self, project_name: str, git_sha: str, component: str | None = None) -> str:
        name = f"{project_name}-{component}" if component else project_name
        return f"{name}:{git_sha[:12]}{self.tag_suffix}"


PROFILES: dict[BuildProfile, ProfileSpec] = {
    BuildProfile.development: ProfileSpec(
        profile=BuildProfile.development,
        tag_suffix="-dev",
        env={"APP_ENV": "development", "NODE_ENV": "development"},
        resource_factor=0.5,
        replicas=1,
    ),
    BuildProfile.release: ProfileSpec(
        profile=BuildProfile.release,
        tag_suffix="",
        env={"APP_ENV": "production", "NODE_ENV": "production"},
        resource_factor=1.0,
        replicas=2,
    ),
}


@dataclass
class BuildResult:
    image_tag: str
    internal_port: int
    log_path: Path
    profile: BuildProfile
    extra_env: dict[str, str] = field(default_factory=dict)


def dockerfile_for(project_type: ProjectType, profile: BuildProfile, workdir: Path) -> Path:
    """리포 자체 Dockerfile 우선, 없으면 타입·프로필별 템플릿."""
    own = workdir / "Dockerfile"
    if own.exists():
        return own
    template = TEMPLATE_DIR / f"{project_type.value}.{profile.value}.Dockerfile"
    if not template.exists():
        raise FileNotFoundError(f"no dockerfile template: {template.name}")
    return template


def script_key(profile: BuildProfile | str, component: str = "") -> str:
    """start_scripts 맵의 키 — `{프로필}:{컴포넌트}`.

    **프로필마다 스크립트가 따로다.** 개발 배포와 운영 배포는 기동 방법이 아예 다르다
    (dev 서버로 띄우기 vs 빌드본 서빙) — 템플릿조차 %PAAS_PROFILE%로 갈라진다. 하나로
    묶으면 사람이나 LLM이 쓴 스크립트도 그 분기를 다시 써야 하고, 한쪽을 고치면 다른 쪽이
    조용히 같이 바뀐다. 컴포넌트는 복합 배포의 유닛이고, 단일 배포는 빈 문자열이다.
    """
    value = profile.value if isinstance(profile, BuildProfile) else str(profile)
    return f"{value}:{component}"


def start_script_for(project: Project | None, component: str = "",
                     profile: BuildProfile | str = BuildProfile.release) -> str:
    """이 프로필·컴포넌트에 쓸 스크립트 본문 — 지정된 것이 있으면 그것, 없으면 템플릿."""
    scripts = (project.start_scripts or {}) if project else {}
    return str(scripts.get(script_key(profile, component)) or "") or _START_SCRIPT


def write_start_script(workdir: Path, project: Project | None = None,
                       component: str = "",
                       profile: BuildProfile | str = BuildProfile.release) -> Path:
    """windows_service 런타임용 start.cmd를 매 배포 시 자동 생성한다.

    기본은 제네릭 템플릿이다 — 타입별 규칙 없이 리포 시그니처로 실행 방법을 추정하며,
    docker의 dockerfile_for가 이미지 빌드를 담당하는 자리를 windows_service에서 대신한다.

    **프로젝트에 지정된 스크립트가 있으면 그것이 이긴다**(Project.start_scripts의 해당
    프로필·컴포넌트 항목 — script_key 참고). 템플릿은 흔한 모양만 맞히므로, 맞지 않는
    프로젝트는 LLM이 리포를 보고 제안한 스크립트를 사람이 확인해 저장한다
    (services/startscript) — 리포에 Dockerfile이 있으면 그것을 쓰는 것과 같은 원칙이다.
    구체적인 의사표시가 추정보다 앞선다.
    """
    path = workdir / START_SCRIPT_NAME
    path.write_text(start_script_for(project, component, profile), encoding="utf-8")
    # vite preview 분기가 --config로 참조한다. node 프로젝트일 때만 쓴다 — 파이썬
    # 프로젝트 작업 디렉터리에 쓸모없는 파일을 남기지 않는다.
    if (workdir / "package.json").exists():
        (workdir / PREVIEW_CONFIG_NAME).write_text(_PREVIEW_CONFIG, encoding="utf-8")
    return path


def env_setup_log_path(project_name: str, git_sha: str, profile: BuildProfile) -> Path:
    """windows_service 런타임의 환경설정(npm/pip install) 로그 파일 경로 — git_sha/profile만
    으로 결정되므로 install_dependencies를 부르기 전에도 미리 계산할 수 있다. docker_build_log_path
    와 같은 이유로 존재한다: deployer.py가 실행 전에 Deployment.build_log_path에 심어 둬야
    설치가 오래 걸리거나 멈춰 있어도 진행 중 로그를 조회할 수 있다."""
    return get_settings().build_log_dir / f"{project_name}-{git_sha[:12]}{PROFILES[profile].tag_suffix}-env.log"


INSTALL_STAMP = "node_modules/.paas-install-stamp"


def _dependency_fingerprint(workdir: Path) -> str:
    """의존성 정의(락파일 우선, 없으면 package.json)의 해시."""
    import hashlib  # noqa: PLC0415

    for name in ("package-lock.json", "npm-shrinkwrap.json", "package.json"):
        f = workdir / name
        if f.exists():
            return hashlib.sha256(f.read_bytes()).hexdigest()
    return ""


def _install_is_current(workdir: Path) -> bool:
    """지난 설치 이후 의존성 정의가 그대로면 True — 다시 설치할 필요가 없다.

    npm ci는 node_modules를 통째로 지우고 처음부터 다시 설치한다. 의존성이 안 바뀌었는데도
    배포마다 그걸 반복하면 시간이 그대로 나가고, 서비스 재기동까지 늦어진다. 지문을
    node_modules 안에 두므로 node_modules를 지우면 지문도 같이 사라진다 — 손으로 지운
    경우에도 자동으로 다시 설치된다.
    """
    stamp = workdir / INSTALL_STAMP
    if not (workdir / "node_modules").is_dir() or not stamp.is_file():
        return False
    try:
        return stamp.read_text(encoding="utf-8").strip() == _dependency_fingerprint(workdir)
    except OSError:
        return False


def _build_script_uses_vite(workdir: Path) -> bool:
    """package.json의 build 스크립트가 실제로 vite를 부르는지.

    node_modules/.bin에 vite가 있는지로 판별하면 안 된다 — npm은 **전이 의존**의 bin도
    최상위 .bin에 호이스팅하므로, vite를 간접적으로만 끌고 오는 Next/webpack 프로젝트도
    통과한다. 그런 프로젝트에 --base를 붙이면 모르는 인자로 빌드가 깨진다.

    또 --base는 npm이 스크립트 **끝**에 이어 붙이므로, vite 명령이 마지막일 때만 그
    인자가 vite에게 간다("vite build && node post.js"면 post.js로 간다).
    """
    import json  # noqa: PLC0415

    try:
        scripts = json.loads((workdir / "package.json").read_text(encoding="utf-8")).get("scripts")
    except (OSError, ValueError, AttributeError):
        return False
    build = (scripts or {}).get("build", "") if isinstance(scripts, dict) else ""
    if not isinstance(build, str) or "vite" not in build:
        return False
    # 마지막 명령이 vite여야 한다. &&·;·| 로 이어진 마지막 조각만 본다.
    import re as _re  # noqa: PLC0415

    last = _re.split(r"&&|\|\||;|\|", build)[-1].strip()
    return last.startswith("vite ") or last == "vite"


def _utf8_env() -> dict:
    """설치 서브프로세스 환경 — **UTF-8 모드를 켠다.**

    pip은 requirements.txt에 BOM이나 PEP-263 쿠키가 없으면 **로케일 인코딩**으로 디코드한다
    (venv에 번들된 구버전 pip은 utf-8을 먼저 시도하지도 않는다). 한국어/서유럽 로케일
    윈도우에서는 한글 주석 한 줄에 UnicodeDecodeError가 나고 설치가 통째로 실패한다 —
    실측으로 세 번 겪었다: 플랫폼 자신의 requirements.txt, supplier-pool(파일 자체가 없었다),
    negowith의 api/requirements.txt(`charmap` codec can't decode byte 0x9d → pip exit 2).
    프로젝트마다 쿠키를 넣게 요구할 일이 아니다. 우리가 pip을 부르므로 우리가 정한다:
    PYTHONUTF8=1이면 locale.getpreferredencoding(False)가 utf-8이 되어 그 폴백이 성립한다.

    PYTHONIOENCODING은 로그를 위해서다 — 설치 출력에 한글이 섞여도 로그 파일이 깨지지 않는다.
    """
    return {**os.environ, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8"}


def install_dependencies(
    workdir: Path, log_path: Path, base_path: str | None = None, build: bool = True,
) -> None:
    """windows_service 런타임의 명시적 환경설정 단계 — npm/pip install을 배포의 build
    단계로 끝내고, 실패하면 배포 자체를 실패로 남긴다(Docker의 build_image와 대응).

    지금까지는 설치가 start.cmd 안에서 앱 기동과 한 프로세스로 묶여 있었다 — 설치가
    오래 걸리면 헬스체크 타임아웃으로만 보였고("의존성 설치가 헬스 타임아웃을 넘기지
    않는지 확인하세요" 라는 힌트가 남던 이유), 실패해도 배포 상태는 실패로 남지 않았다
    (start.cmd는 설치 실패 후에도 다음 줄로 계속 진행한다). 여기서 헬스체크 창 밖에서
    먼저 끝내면 그 모호함이 없어진다.

    base_path는 이 배포가 외부에서 열리는 서브패스(/apps/{조직}/{프로젝트}[~dev]/)다.
    프록시가 그 접두어를 벗기고 넘기므로 앱은 내부적으로 "/"를 받지만, 브라우저가 보는
    주소는 서브패스다 — 프런트엔드를 기본값(base="/")으로 빌드하면 HTML이 자산을
    /assets/...로 참조하고, 그 요청은 어떤 라우팅에도 안 걸려 404가 된다(제목만 뜨는
    빈 화면). Vite 프로젝트일 때만 빌드에 --base로 넘긴다.

    설치와 빌드가 **모두** 여기에 있다는 점이 중요하다. 예전에는 start.cmd도 같은
    설치·빌드를 한 번 더 했는데, start.cmd는 배포 때만이 아니라 서비스가 뜰 때마다
    실행되므로 재부팅·SW 업데이트·크래시 재시작마다 반복됐다. "이미 설치돼 있으면
    빠르게 통과"할 거라 봤지만 npm ci는 node_modules를 통째로 지우고 처음부터 다시
    설치한다 — 통과가 아니라 전체 재설치다.
    """
    timeout_seconds = get_settings().build_timeout_seconds
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, "a", encoding="utf-8") as log:
        if (workdir / "package.json").exists():
            # Windows에서 npm은 npm.cmd(배치 스크립트)다 — shell=False로 CreateProcess를
            # 직접 부르면(subprocess 기본값) PATHEXT의 .cmd 확장자를 찾아주지 않아 PATH에
            # npm이 있어도 "파일을 찾을 수 없다"고 실패한다(cmd.exe·PowerShell에서 직접
            # 치면 되는 이유는 셸이 PATHEXT를 뒤져서다). shutil.which로 먼저 실제
            # 경로(npm.cmd 포함)를 찾아 그 경로로 실행한다 — POSIX에서는 원래도 동작하던
            # 그대로다.
            npm_exe = shutil.which("npm")
            if npm_exe is None:
                raise BuildError(
                    "npm 실행 파일을 PATH에서 찾을 수 없습니다. paas를 nssm 등 Windows "
                    "서비스로 띄웠다면, 그 서비스 계정의 PATH는 로그인해서 쓰는 사용자의 "
                    "PATH와 다를 수 있습니다 — 서비스가 보는 PATH(nssm set paas "
                    "AppEnvironmentExtra 또는 시스템 환경변수)에 Node.js 설치 경로가 있는지 "
                    "확인하세요.",
                    log_path,
                )
            # --include=dev를 붙이는 이유 — vite·tsc 같은 빌드 도구는 devDependencies에
            # 있는데, 환경에 NODE_ENV=production이 있거나 .npmrc에 omit=dev/production이
            # 있으면 npm이 그걸 통째로 건너뛴다(node_modules/.bin 자체가 안 생긴다).
            # 그러면 빌드가 "'vite' is not recognized"로 죽는다. 이 설치는 paas 서비스
            # 프로세스의 환경을 그대로 상속하므로 서버 설정 하나에 배포가 끌려다닌다 —
            # CLI 플래그가 환경변수·.npmrc보다 우선하므로 여기서 못박는다.
            # (설치 후 prune도 하지 않는다 — vite preview로 서빙하는 경우 vite가 실행
            #  시점에도 필요하다.)
            if _install_is_current(workdir):
                log.write("[env-setup] 의존성 변경 없음 — 설치를 건너뜁니다.\n")
                log.flush()
            else:
                base = (
                    [npm_exe, "ci"] if (workdir / "package-lock.json").exists()
                    else [npm_exe, "install"]
                )
                npm_cmd = [*base, "--include=dev"]
                log.write(f"[env-setup] {' '.join(npm_cmd)} (cwd={workdir})\n")
                log.flush()
                try:
                    proc = subprocess.run(
                        npm_cmd, cwd=workdir, stdout=log, stderr=subprocess.STDOUT,
                        timeout=timeout_seconds,
                    )
                except OSError as e:
                    raise BuildError(f"npm 실행 실패: {e}", log_path) from e
                except subprocess.TimeoutExpired as e:
                    raise BuildError(
                        f"npm install이 {timeout_seconds}초 내에 끝나지 않아 중단했습니다 "
                        "(PAAS_BUILD_TIMEOUT_SECONDS로 늘릴 수 있습니다).", log_path,
                    ) from e
                if proc.returncode != 0:
                    raise BuildError(f"npm install 실패 (exit {proc.returncode})", log_path)
                # 성공한 뒤에만 남긴다 — 실패한 설치를 "최신"으로 기억하면 안 된다.
                # 지문을 못 남겨도 배포는 성공이다(다음 배포에 한 번 더 설치할 뿐) —
                # 의존성이 없는 package.json이면 npm이 node_modules를 안 만들 수도 있다.
                stamp = workdir / INSTALL_STAMP
                try:
                    stamp.parent.mkdir(parents=True, exist_ok=True)
                    stamp.write_text(_dependency_fingerprint(workdir), encoding="utf-8")
                except OSError as e:
                    log.write(f"[env-setup] 설치 지문을 남기지 못했습니다: {e}\n")
                    log.flush()

            # 빌드도 여기서 끝낸다. start.cmd에 두면 서비스가 뜰 때마다(재부팅·재시작
            # 포함) 다시 빌드하고, 실패해도 배포는 성공으로 남는다 — 이 단계에서 하면
            # 실패가 배포 실패로 드러난다. --if-present는 npm run의 정식 옵션이라
            # build 스크립트가 없는 프로젝트에서는 조용히 넘어간다.
            # dev 프로필은 빌드하지 않는다 — dev 서버가 소스를 즉석에서 변환해 서빙하므로
            # 빌드 산출물을 쓰지 않고, 배포마다 도는 빌드가 그대로 낭비다.
            build_cmd = [npm_exe, "run", "build", "--if-present"] if build else None
            # --base는 Vite 옵션이라 Vite 프로젝트에만 붙인다 — webpack/next 등에 넘기면
            # 모르는 인자로 빌드가 깨진다. 설치가 끝난 뒤라 .bin 존재 여부로 판별할 수 있다.
            if build_cmd is None:
                # return을 쓰면 아래 requirements.txt 단계까지 건너뛴다 — 두 파일을 다
                # 가진 프로젝트에서 pip 설치가 통째로 빠진다.
                log.write("[env-setup] dev 프로필 — 빌드를 건너뜁니다(dev 서버가 서빙).\n")
                log.flush()
            elif base_path and _build_script_uses_vite(workdir):
                build_cmd += ["--", f"--base={base_path}"]
            if build_cmd is not None:
                log.write(f"[env-setup] {' '.join(build_cmd)} (cwd={workdir})\n")
                log.flush()
                try:
                    proc = subprocess.run(
                        build_cmd,
                        cwd=workdir, stdout=log, stderr=subprocess.STDOUT,
                        timeout=timeout_seconds,
                    )
                except subprocess.TimeoutExpired as e:
                    raise BuildError(
                        f"npm run build가 {timeout_seconds}초 내에 끝나지 않아 중단했습니다 "
                        "(PAAS_BUILD_TIMEOUT_SECONDS로 늘릴 수 있습니다).", log_path,
                    ) from e
                if proc.returncode != 0:
                    raise BuildError(f"npm run build 실패 (exit {proc.returncode})", log_path)

        if (workdir / "requirements.txt").exists():
            venv_dir = workdir / ".venv"
            if not venv_dir.exists():
                log.write("[env-setup] python -m venv .venv\n")
                log.flush()
                try:
                    proc = subprocess.run(
                        [sys.executable, "-m", "venv", str(venv_dir)],
                        cwd=workdir, stdout=log, stderr=subprocess.STDOUT,
                        timeout=timeout_seconds, env=_utf8_env(),
                    )
                except subprocess.TimeoutExpired as e:
                    raise BuildError(
                        f"venv 생성이 {timeout_seconds}초 내에 끝나지 않아 중단했습니다.", log_path,
                    ) from e
                if proc.returncode != 0:
                    raise BuildError(f"venv 생성 실패 (exit {proc.returncode})", log_path)
            venv_python = venv_dir / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
            log.write("[env-setup] pip install -r requirements.txt\n")
            log.flush()
            try:
                proc = subprocess.run(
                    [str(venv_python), "-m", "pip", "install", "--disable-pip-version-check",
                     "-r", "requirements.txt"],
                    cwd=workdir, stdout=log, stderr=subprocess.STDOUT,
                    timeout=timeout_seconds, env=_utf8_env(),
                )
            except FileNotFoundError as e:
                raise BuildError(f"venv python을 찾을 수 없습니다: {e}", log_path) from e
            except subprocess.TimeoutExpired as e:
                raise BuildError(
                    f"pip install이 {timeout_seconds}초 내에 끝나지 않아 중단했습니다 "
                    "(PAAS_BUILD_TIMEOUT_SECONDS로 늘릴 수 있습니다).", log_path,
                ) from e
            if proc.returncode != 0:
                raise BuildError(f"pip install 실패 (exit {proc.returncode})", log_path)


def internal_port(project_type: ProjectType, profile: BuildProfile) -> int:
    return INTERNAL_PORTS[(project_type, profile)]


def docker_build_log_path(
    project_name: str, git_sha: str, profile: BuildProfile, component: str | None = None,
) -> Path:
    """docker build 로그 파일 경로 — git_sha/profile/component만으로 결정되므로 빌드를
    시작하기 전에도 미리 계산할 수 있다. deployer.py가 이 값을 Deployment.build_log_path에
    빌드 시작 전에 심어 둬야, 진행 중에도(빌드가 오래 걸리거나 멈춰 있어도) 그 시점까지의
    로그를 조회할 수 있다."""
    spec = PROFILES[profile]
    log_name = f"{project_name}{f'-{component}' if component else ''}-{git_sha[:12]}{spec.tag_suffix}.log"
    return get_settings().build_log_dir / log_name


def build_image(
    project: Project,
    workdir: Path,
    git_sha: str,
    profile: BuildProfile,
    *,
    component: str | None = None,
    component_type: ProjectType | None = None,
    context_subdir: str | None = None,
) -> BuildResult:
    """component가 주어지면(복합 배포) 태그·로그 파일명에 컴포넌트명을 붙여 일반 프로젝트와
    충돌하지 않게 한다. 빌드 컨텍스트는 context_subdir(없으면 component와 같은 이름의 폴더).

    **이름과 경로를 나눠 받는 이유.** 감지된 컴포넌트 경로는 `apps/web`처럼 슬래시를 담을
    수 있는데(services/structure), 그 값을 그대로 태그에 쓰면 `proj-apps/web:sha`가 되어
    docker 태그로 유효하지 않고 로그 파일명에도 못 쓴다. 이름은 슬래시가 없는 값
    (`apps-web`)이고, 경로는 빌드 컨텍스트로만 쓴다.

    component가 없고 project.source_subdir가 지정된 경우(모노레포 서브폴더 프로젝트)는
    workdir/{source_subdir}를 빌드 컨텍스트로 쓴다 — 태그·포트 매핑은 일반 프로젝트와 동일."""
    settings = get_settings()
    spec = PROFILES[profile]
    build_type = component_type or project.type
    if component:
        subdir = context_subdir if context_subdir is not None else component
        context_dir = workdir if subdir in ("", ".") else workdir / subdir
    elif project.source_subdir:
        context_dir = workdir / project.source_subdir
    else:
        context_dir = workdir
    tag = spec.image_tag(project.name, git_sha, component=component)
    dockerfile = dockerfile_for(build_type, profile, context_dir)

    log_path = docker_build_log_path(project.name, git_sha, profile, component)
    cmd = [
        "docker", "build",
        "-f", str(dockerfile),
        "-t", tag,
        "--build-arg", f"APP_PROFILE={profile.value}",
        str(context_dir),
    ]
    with open(log_path, "w", encoding="utf-8") as log:
        try:
            proc = subprocess.run(
                cmd, stdout=log, stderr=subprocess.STDOUT, timeout=settings.build_timeout_seconds,
            )
        except FileNotFoundError as e:
            raise BuildError(f"[WinError 2] docker CLI 실행 파일을 찾을 수 없습니다: {e}", log_path) from e
        except subprocess.TimeoutExpired as e:
            raise BuildError(
                f"docker build가 {settings.build_timeout_seconds}초 내에 끝나지 않아 중단했습니다 "
                "(PAAS_BUILD_TIMEOUT_SECONDS로 늘릴 수 있습니다).", log_path,
            ) from e
    if proc.returncode != 0:
        raise BuildError(f"docker build failed (exit {proc.returncode})", log_path)

    return BuildResult(
        image_tag=tag,
        internal_port=internal_port(build_type, profile),
        log_path=log_path,
        profile=profile,
        extra_env=dict(spec.env),
    )


COMPOSITE_COMPONENTS: tuple[str, str] = ("backend", "frontend")


def detect_composite_components(workdir: Path) -> dict[str, ProjectType] | None:
    """backend/, frontend/ 서브폴더가 둘 다 있어야 composite로 인정한다(하나만 있으면
    일반 단일 프로젝트로 취급 — None 반환). 각 서브폴더의 실제 타입은 시그니처 파일로
    추론하고, 추론 불가면 ValueError로 명확히 실패한다(추측성 기본값 금지)."""
    dirs = {name: workdir / name for name in COMPOSITE_COMPONENTS}
    if not all(d.is_dir() for d in dirs.values()):
        return None
    return {name: _detect_component_type(d) for name, d in dirs.items()}


def detect_project_type(workdir: Path) -> ProjectType | None:
    """리포 루트만 보고 프로젝트 타입을 추론한다(services/gitea_sync.py 전용 — Gitea에서
    기존 리포를 가져올 때 사용자가 type을 지정하지 않으므로). backend/, frontend/가
    둘 다 있으면 composite, 그 외엔 _detect_component_type과 동일한 시그니처 규칙.
    추론 불가하면 None(추측성 기본값 금지 — 호출부가 건너뛰고 보고해야 한다)."""
    if detect_composite_components(workdir) is not None:
        return ProjectType.composite
    try:
        return _detect_component_type(workdir)
    except ValueError:
        return None


def _detect_component_type(component_dir: Path) -> ProjectType:
    if (component_dir / "requirements.txt").exists() or (component_dir / "pyproject.toml").exists():
        return ProjectType.python
    package_json = component_dir / "package.json"
    if package_json.exists():
        try:
            manifest = json.loads(package_json.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            manifest = {}
        deps = {**manifest.get("dependencies", {}), **manifest.get("devDependencies", {})}
        return ProjectType.react if "react" in deps else ProjectType.node
    if (component_dir / "index.html").exists():
        return ProjectType.html
    raise ValueError(
        f"컴포넌트 타입을 추론할 수 없습니다: {component_dir} "
        "(requirements.txt/pyproject.toml, package.json, index.html 중 하나가 필요합니다)"
    )


class BuildError(RuntimeError):
    def __init__(self, message: str, log_path: Path | None = None):
        super().__init__(message)
        self.log_path = log_path


def checkout(project: Project, git_sha: str | None = None) -> tuple[Path, str]:
    """clone 또는 pull 후 (작업 디렉토리, 해석된 커밋 SHA)를 반환한다."""
    settings = get_settings()
    workdir = settings.work_dir / project.name
    if not (workdir / ".git").exists():
        shutil.rmtree(workdir, ignore_errors=True)
        _run_git(["clone", "--branch", project.branch, project.git_url, str(workdir)],
                  git_url=project.git_url)
    else:
        _run_git(["fetch", "origin", project.branch], cwd=workdir, git_url=project.git_url)
        _run_git(["checkout", project.branch], cwd=workdir)
        _run_git(["reset", "--hard", f"origin/{project.branch}"], cwd=workdir)
    if git_sha:
        _run_git(["checkout", git_sha], cwd=workdir)
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=workdir, capture_output=True, **_TEXT, check=True
        )
    except FileNotFoundError as e:
        raise BuildError(f"[WinError 2] git 실행 파일을 찾을 수 없습니다: {e}") from e
    return workdir, out.stdout.strip()


def _run_git(args: list[str], cwd: Path | None = None, git_url: str | None = None) -> None:
    auth = auth_args(git_url) if git_url else []
    try:
        proc = subprocess.run(["git", *auth, *args], cwd=cwd, capture_output=True, **_TEXT)
    except FileNotFoundError as e:
        raise BuildError(f"[WinError 2] git 실행 파일을 찾을 수 없습니다: {e}") from e
    if proc.returncode != 0:
        raise BuildError(f"git {args[0]} failed: {proc.stderr.strip()[:500]}")
